parameters:
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: appNamePrefix
  type: string
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: checkoutDevopsStep
  type: step
  default:
    script: echo dummy step
- name: enableKeyVault
  type: boolean
  default: false
- name: enableStagingSlot
  type: boolean
  default: false
- name: customDomainNames
  type: object
  default: []
- name: customDomainNameManagedCertificate
  type: boolean
  default: false
- name: functionRuntime
  type: string
  default: 'dotnet-isolated'  
- name: allowedOrigins
  type: object
  default: []
- name: dotnetVersion
  type: string
  default: '8'

jobs:
- job: Infrastructure
  condition: succeeded()
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}
  steps:
  - ${{ parameters.checkoutDevopsStep }}

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Infrastructure Provisioning'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: ${{ parameters.azureServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resourceGroupName }}
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)/bicep/FunctionApp.bicep'
      overrideParameters: >-
        -appNamePrefix ${{ parameters.appNamePrefix }}
        -enableKeyVault ${{ convertToJson(parameters.enableKeyVault) }}
        -enableStagingSlot ${{ convertToJson(parameters.enableStagingSlot) }}
        -customDomainNames ${{ convertToJson(parameters.customDomainNames) }}
        -customDomainNameManagedCertificate ${{ convertToJson(parameters.customDomainNameManagedCertificate) }}
        -allowedOrigins ${{ convertToJson(parameters.allowedOrigins) }}
        -dotnetVersion ${{ parameters.dotnetVersion }}
      deploymentMode: 'Incremental'
      deploymentName: 'DeployPipelineTemplate'
      deploymentOutputs: 'infrastructureProvisioningResult'

  - template: ../steps/parseBicepResult.yml
    parameters:
      inputJSONValue: '$(infrastructureProvisioningResult)'
      outputVariableName: 'infrastructureOutputs'

- job: AppSettings
  dependsOn: Infrastructure
  condition: succeeded()
  variables:
    functionAppName: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppName']]
    functionAppContentShareName: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppContentShareName']]
    storageAccountConnectionString: $[dependencies.Infrastructure.outputs['infrastructureOutputs.storageAccountConnectionString']]  
    applicationInsightsInstrumentationKey: $[dependencies.Infrastructure.outputs['infrastructureOutputs.applicationInsightsInstrumentationKey']]
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}
  steps:
  - task: AzureAppServiceSettings@1
    displayName: 'Update AppSettings'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      appName: $(functionAppName)
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appSettings: |
        [
          {
            "name": "AzureWebJobsStorage",
            "value": "$(storageAccountConnectionString)",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
            "value": "$(storageAccountConnectionString)",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_CONTENTSHARE",
            "value": "$(functionAppContentShareName)",
            "slotSetting": false
          },
          {
            "name": "FUNCTIONS_EXTENSION_VERSION",
            "value": "~4",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_NODE_DEFAULT_VERSION",
            "value": "~14",
            "slotSetting": false
          },
          {
            "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
            "value": "$(applicationInsightsInstrumentationKey)",
            "slotSetting": false
          },
          {
            "name": "FUNCTIONS_WORKER_RUNTIME",
            "value": "${{ parameters.functionRuntime }}",
            "slotSetting": false
          }
        ]
