parameters:
- name: serviceConnectionId
  type: string
- name: resourceGroupName
  type: string
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: enableStagingSlot
  type: boolean
  default: false

jobs:
- deployment: Deploy
  displayName: Deploy
  dependsOn: Infrastructure
  condition: succeeded()
  environment: 'production'
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}
  variables:
    functionAppName: $[ dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppName'] ]  

  strategy:
    runOnce:
      deploy:
        steps: 
        - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]production"
          displayName: "Deploy to Production"
          condition: eq('${{ parameters.enableStagingSlot }}', false)

        - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]staging"
          displayName: "Deploy to Staging"
          condition: eq('${{ parameters.enableStagingSlot }}', true)

        - task: AzureFunctionApp@2
          displayName: 'Functions Deploy'
          inputs:
            azureSubscription: ${{ parameters.serviceConnectionId }}
            resourceGroupName: ${{ parameters.resourceGroupName }}
            appType: functionApp
            appName: $(functionAppName)
            slotName: $(slotName)
            deployToSlotOrASE: ${{ parameters.enableStagingSlot }}
            package: '$(Pipeline.Workspace)/drop/function-app-$(Build.BuildNumber).zip'
