parameters:
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: azureServiceConnection
  type: string
- name: sourceDir
  type: string
  default: 'src'
- name: dropDir
  type: string
  default: '$(Build.ArtifactStagingDirectory)'
- name: checkoutDevopsStep
  type: step

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}

  steps:
  - checkout: self
    path: $(System.DefaultWorkingDirectory)\website

  - ${{ parameters.checkoutDevopsStep }}
    
  - task: AzurePowerShell@5
    displayName: 'Expand HTML includes'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnection }}'
      scriptType: 'InlineScript'
      Inline: |
        dir $(System.DefaultWorkingDirectory)
        $(System.DefaultWorkingDirectory)\Cod.Infrastructures\scripts\expand-html-includes.ps1 -Root '$(System.DefaultWorkingDirectory)\website\${{ parameters.sourceDir }}'
      azurePowerShellVersion: 'latestVersion'
      pwsh: true

  - task: CopyFiles@2
    displayName: 'Drop Static Website'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)\website\${{ parameters.sourceDir }}'
      Contents: '**'
      TargetFolder: '${{ parameters.dropDir }}'
    
  - publish: '${{ parameters.sourceDir }}'
    artifact: drop
