parameters:
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: sourceDir
  type: string
- name: dropDir
  type: string
- name: checkoutDevopsStep
  type: step

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}

  steps:
  - ${{ parameters.checkoutDevopsStep }}
- 
  - task: AzurePowerShell@5
    displayName: 'Expand HTML includes'
    inputs:
    scriptType: 'InlineScript'
    Inline: |
        $(System.DefaultWorkingDirectory)/scripts/expand-html-includes.ps1 -Root '${{ parameters.sourceDir }}'
    azurePowerShellVersion: 'latestVersion'
    pwsh: true

  - task: CopyFiles@2
    displayName: 'Drop Static Website'
    inputs:
      SourceFolder: '${{ parameters.sourceDir }}'
      Contents: '**'
      TargetFolder: '${{ parameters.dropDir }}'
    
  - publish: '${{ parameters.sourceDir }}'
    artifact: drop
