parameters:
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: azureServiceConnection
  type: string
- name: sourceDir
  type: string
  default: 'src'
- name: includesDir
  type: string
  default: 'includes'
- name: dropDir
  type: string
  default: '$(Build.ArtifactStagingDirectory)'
- name: checkoutDevopsSteps
  type: stepList

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}

  steps:
  - checkout: self
    path: website
    
  - ${{ each step in parameters.checkoutDevopsSteps }}:
      - ${{ step }}

  - task: AzurePowerShell@5
    displayName: 'Expand HTML includes'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnection }}'
      scriptType: 'InlineScript'
      Inline: |
        .\scripts\expand-html-includes.ps1 -Source '..\website\${{ parameters.sourceDir }}' -Includes '..\website\${{ parameters.includesDir }}'
      azurePowerShellVersion: 'latestVersion'
      pwsh: true

  - task: CopyFiles@2
    displayName: 'Drop Static Website'
    inputs:
      SourceFolder: '..\website\${{ parameters.sourceDir }}'
      Contents: '**'
      TargetFolder: '${{ parameters.dropDir }}'
    
  - publish: '${{ parameters.dropDir }}'
    artifact: drop
