parameters:
- name: serviceConnectionId
  type: string
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: storageAccountName
  type: string
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: checkoutDevopsStep
  type: step
  default:
    script: echo dummy step
- name: enableCdn
  type: boolean
  default: false
- name: cdnCustomDomainName
  type: string
  default: ''

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: 'production'
  pool:
    vmImage: ${{ parameters.buildAgentVmImage }}
  variables:
    cdnProfileName: '${{ parameters.storageAccountName }}cdn'
    cdnEndpointName: '${{ parameters.storageAccountName }}endpoint'

  strategy:
    runOnce:
      deploy:
        steps: 
        - ${{ parameters.checkoutDevopsStep }}

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Infrastructure'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '${{ parameters.azureServiceConnection }}'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '${{ parameters.resourceGroupName }}'
            location: '$(location)'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/bicep/StaticWebsite.bicep'
            overrideParameters: >-
              -storageAccountName ${{ parameters.storageAccountName }}
              -profileName $(cdnProfileName)
              -endpointName $(cdnEndpointName)
              -enableCdn ${{ convertToJson(parameters.enableCdn) }}
            deploymentMode: 'Incremental'
            deploymentName: 'DeployPipelineTemplate'
            deploymentOutputs: 'bicepOutputs'
            
        - task: AzurePowerShell@4
          displayName: 'Infrastructure Details'
          inputs:
            azureSubscription: '${{ parameters.azureServiceConnection }}'
            scriptType: 'InlineScript'
            Inline: |
              Write-Host '$(bicepOutputs)'
            azurePowerShellVersion: 'latestVersion'
            pwsh: true
            
        - task: AzureFileCopy@3
          displayName: 'File Copy'
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/src'
            azureSubscription: '${{ parameters.azureServiceConnection }}'
            Destination: AzureBlob
            storage: ${{ parameters.resourceGroupName }}
            ContainerName: '$web'
            CleanTargetBeforeCopy: true

        - task: AzureCLI@2
          displayName: 'Purge CDN'
          condition: and(succeeded(), eq('${{ parameters.enableCdn }}', true))
          inputs:
            azureSubscription: '${{ parameters.azureServiceConnection }}'
            scriptType: "ps"
            scriptLocation: inlineScript
            inlineScript: |
              az cdn endpoint purge -g ${{ parameters.resourceGroupName }} --profile-name $(cdnProfileName) --name $(cdnEndpointName) --no-wait --content-paths "/*"

        - task: AzurePowerShell@5
          displayName: 'Custom Domain'
          condition: and(succeeded(), eq('${{ parameters.enableCdn }}', true), ne('${{ parameters.cdnCustomDomainName }}', ''))
          inputs:
            azureSubscription: '${{ parameters.azureServiceConnection }}'
            ScriptType: 'InlineScript'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
            Inline: |
              $resourceGroupName = '${{ parameters.resourceGroupName }}'
              $profileName = '$(cdnProfileName)'
              $endpointName = '$(cdnEndpointName)'
              $customDomainName = '${{ parameters.cdnCustomDomainName }}'
              $customDomainSymbolicName = $customDomainName.Replace('.', '-')
              $domains = Get-AzCdnCustomDomain -ResourceGroupName $resourceGroupName -ProfileName $profileName -EndpointName $endpointName
              if ($domains.Count -eq 0) {
                  New-AzCdnCustomDomain -ResourceGroupName $resourceGroupName -ProfileName $profileName -EndpointName $endpointName -Name   $customDomainSymbolicName -HostName $customDomainName
                  $customDomainHttpsParam = New-AzCdnManagedHttpsParametersObject -CertificateSource Cdn -ProtocolType ServerNameIndication -  CertificateSourceParameterCertificateType Dedicated
                  Enable-AzCdnCustomDomainCustomHttps -CustomDomainHttpsParameter $customDomainHttpsParam -CustomDomainName   $customDomainSymbolicName -ResourceGroupName $resourceGroupName -ProfileName $profileName -EndpointName $endpointName -NoWait
              }