parameters:
- name: serviceConnectionId
  type: string
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: appNamePrefix
  type: string
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: nugetVSTSFeedID
  type: string
  default: ''
- name: checkoutDevopsStep
  type: step
  default:
    script: echo dummy step
- name: enableKeyVault
  type: boolean
  default: false
- name: projectToPublish
  type: string
  default: '**/*.csproj'
- name: enableStagingSlot
  type: boolean
  default: false
- name: customDomainName
  type: string
  default: ''
- name: customDomainNameManagedCertificate
  type: boolean
  default: false
- name: functionRuntime
  type: string
  default: 'dotnet-isolated'
- name: dotnetVersion
  type: string
  default: '7.x'

stages:
- stage: Build
  jobs:
  - template: jobs/FunctionAppBuild.yml
    parameters:
      buildAgentVmImage: ${{ parameters.buildAgentVmImage }}
      nugetVSTSFeedID: ${{ parameters.nugetVSTSFeedID }}
      projectToPublish: ${{ parameters.projectToPublish }}
      dotnetVersion: ${{ parameters.dotnetVersion }}

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: jobs/FunctionAppDeploy.yml
    parameters:
      serviceConnectionId: ${{ parameters.serviceConnectionId }}
      azureServiceConnection: ${{ parameters.azureServiceConnection }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appNamePrefix: ${{ parameters.appNamePrefix }}
      buildAgentVmImage: ${{ parameters.buildAgentVmImage }}
      checkoutDevopsStep: ${{ parameters.checkoutDevopsStep }}
      enableKeyVault: ${{ parameters.enableKeyVault }}
      enableStagingSlot: ${{ parameters.enableStagingSlot }}
      customDomainName: ${{ parameters.customDomainName }}
      customDomainNameManagedCertificate: ${{ parameters.customDomainNameManagedCertificate }}
      functionRuntime: ${{ parameters.functionRuntime }}