parameters:
- name: serviceConnectionId
  type: string
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: appNamePrefix
  type: string
- name: buildAgentVmImage
  type: string
  default: 'windows-latest'
- name: checkoutDevopsStep
  type: step
  default:
    script: echo dummy step
- name: enableKeyVault
  type: boolean
  default: false
- name: projectToPublish
  type: string
  default: '**/*.csproj'

stages:
- stage: Build
  jobs:
  - template: jobs/FunctionAppBuild.yml
    parameters:
      buildAgentVmImage: ${{ parameters.buildAgentVmImage }}
      projectToPublish: ${{ parameters.projectToPublish }}

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: jobs/FunctionAppDeploy.yml
    parameters:
      serviceConnectionId: ${{ parameters.serviceConnectionId }}
      azureServiceConnection: ${{ parameters.azureServiceConnection }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appNamePrefix: ${{ parameters.appNamePrefix }}
      buildAgentVmImage: ${{ parameters.buildAgentVmImage }}
      checkoutDevopsStep: ${{ parameters.checkoutDevopsStep }}
      enableKeyVault: ${{ parameters.enableKeyVault }}