parameters:
- name: serviceConnectionId
  type: string
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: functionAppName
  type: string

stages:
- template: FunctionAppBuild.yml
- template: FunctionAppDeploy.yml
  parameters:
      serviceConnectionId: ${{ parameters.serviceConnectionId }}
      azureServiceConnection: ${{ parameters.azureServiceConnection }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      functionAppName: ${{ parameters.functionAppName }}