parameters:
- name: serviceConnectionId
  type: string
- name: azureServiceConnection
  type: string
- name: resourceGroupName
  type: string
- name: functionAppName
  type: string

stages:
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'production'
    pool:
      vmImage: windows-latest

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Infrastructure Provisioning'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ azureServiceConnection }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: ${{ resourceGroupName }}
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/$(templateFile)'
              overrideParameters: '-appName ${{ functionAppName }}'
              deploymentMode: 'Incremental'
              deploymentName: 'DeployPipelineTemplate'

          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: ${{ serviceConnectionId }}
              resourceGroupName: ${{ resourceGroupName }}
              appType: functionApp
              appName: ${{ functionAppName }}
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'